### ISSUE TITLE
FHIR Path .as(DateTime) is not evaluating correctly

### ISSUE THREAD

**Issue by jackliums** [ewoutkramer/fhir-net-api#681] opened 2018-09-10 17:15 UTC
I am using 0.96.0 version of the NuGet package and it seems like FHIR Path with .as(DateTime) is not evaluating correctly.

Sample observation is loaded from here:
http://hl7.org/fhir/observation-example-date-lastmp.json.html

For the code-value-date composite search parameter, the components are defined as:

``` json
        "code": "code-value-date",
        "base": [
          "Observation"
        ],
        "type": "composite",
        "description": "Code and date/time value parameter pair",
        "expression": "Observation",
        "xpathUsage": "normal",
        "component": [
          {
            "definition": {
              "reference": "http://hl7.org/fhir/SearchParameter/clinical-code"
            },
            "expression": "code"
          },
          {
            "definition": {
              "reference": "http://hl7.org/fhir/SearchParameter/Observation-value-date"
            },
            "expression": "value.as(DateTime) | value.as(Period)"
          }
        ]
```
The value does not seem to evaluate correctly. `Observation.value` evaluates to `FhirDateTime`, but `Observation.value.as(DateTime)` evaluates to empty.

```
resource.Select("Observation.value").FirstOrDefault()
{"2016-12-30"}
    Children: {Hl7.Fhir.Model.Element.<get_Children>d__14}
    ElementId: null
    Extension: Count = 0
    FhirComments: {System.Linq.Enumerable.SelectListIterator<Hl7.Fhir.Model.FhirString, string>}
    FhirCommentsElement: Count = 0
    ObjectValue: "2016-12-30"
    TypeName: "dateTime"
    UserData: Count = 0
    Value: "2016-12-30"

resource.Select("Observation.value.as(DateTime)").FirstOrDefault()
null
```

**Comment by ewoutkramer** [comment] 2018-09-26 10:04
That looks like a bug indeed. I'll take a look.

Note: as C# developers, we tend to think `|` is the OR, but in fact, in FhirPath, it's an array concatenation operator.  Change your expression to use `or` instead of `|`.  (not that that is the cause of the error ;-)).

**Comment by jackliums** [comment] 2018-09-26 16:29
The snippet of definition ```value.as(DateTime) | value.as(Period)``` is from the official FHIR Definitions published here: http://hl7.org/fhir/definitions.json.zip and ```|``` is used all over the place. Are you saying that it's a bug with the published spec?

**Comment by ewoutkramer** [comment] 2018-09-27 10:05
Yes. We have fixed it in several places at build.fhir.org (for R4), but this may linger around for a good while...

**Comment by ewoutkramer** [comment] 2018-09-27 10:12
In fact, I don't think HL7 will ever fix this in the older releases, so we should do it in our own distributions. I have created #718 to make sure we do.

**Comment by brianpos** [comment] 2018-09-27 10:18
That wouldn't actually cause a bug I don't think. 
As the value is not multi cardinality, the result would be selecting the expected value.

**Comment by ewoutkramer** [comment] 2018-09-27 10:19
Yeah, but that's accidental rather than intentional ;-)

**Comment by ewoutkramer** [comment] 2018-11-20 17:05
It could well be this is caused by the fact that the instance type is "dateTime", but the FhirPath statement uses "DateTime".  Since dateTime is a primitive, this is actually incorrect.

**Comment by ewoutkramer** [comment] 2018-11-22 12:48
Found these errors in STU3:

* (almost all resources): ele-1:  <expression value="hasValue() | (children().count() &gt; id.count())" /> => shoud use 'or' instead of '|'
* search-parameters.xml: <expression value="value.as(DateTime) | value.as(Period)" />  => should be as(dateTime)

**Comment by ewoutkramer** [comment] 2018-11-22 17:17
Fixed by #776

**Closed by ewoutkramer** 2018-11-22 17:17 UTC
Labels: bug

**Comment by brianpos** [comment] 2018-11-23 08:02
Hoping the fix was to the casing of Date Time rather than the or | as that works anyway.

**Comment by ewoutkramer** [comment] 2018-11-25 21:40
It was to the dateTime/DateTime - the | was incorrect in ele-1 - corrected that as well.

**Comment by brianpos** [comment] 2018-11-25 21:45
Yup, thanks. Can see now too.
