### ISSUE TITLE
Validation yields different results

### ISSUE THREAD

**Issue by jkiddo** [ewoutkramer/fhir-net-api#438] opened 2017-10-11 14:15 UTC
Please see https://github.com/jamesagnew/hapi-fhir/issues/757

While I know that your frameworks (HAPI and this) are different in many aspects, I would expect the validation part to be sort of streamlined in some aspects. It does however not look like to be the case.

**Comment by ewoutkramer** [comment] 2017-10-12 12:24
To be clear, the output *should* of course be "the same". Maybe not literally, but yes, the same things should be considered correct or incorrect.

This is not currently the case, for (at least) two reasons:
* The implementation of Java and C# have been done independently - without copying each others code.
* The spec is (almost on purpose) unclear on some aspects - giving rise to multiple "correct" interpretations.

In this fase of FHIR, this is important to us, since these differences are a major source of feedback to indicate where the spec is unclear.  

That being said, we are looking at developing a set of testcases which would test behaviour of both/all validators and make sure the output is the same.  This will help future implementers (on different platforms) to make sure they align and don't have to go through the same process as both Grahame and I do now.

So, I will probably get back to you to get more details on the differences in this specific case to find out who's wrong, why and whether this means the spec should be updated.

**Comment by wmrutten** [comment] 2017-10-16 09:10
Maybe AEGIS could implement validation engine testing into TouchStone?
This would allow different implementations to be verified and compared.

**Comment by ewoutkramer** [comment] 2017-10-23 12:51
See also #353 ;-)

**Comment by ewoutkramer** [comment] 2018-11-22 22:37
I'll mark this as a duplicate of #353.

**Closed by ewoutkramer** 2018-11-22 22:37 UTC
Labels: [Validator], duplicate, needs research
