### ISSUE TITLE
Meta action cannot handle operation outcome

### ISSUE THREAD

**Issue by mharthoorn** [ewoutkramer/fhir-net-api#68] opened 2015-04-21 09:20 UTC
When the Meta action "resource/id/$meta" gets an error with a OperationOutcome the response is "Body returned by server cannot be parsed"

**Comment by ewoutkramer** [comment] 2015-06-25 11:18
I think this is a duplicate of #64. See if I hit this code and maybe you can reverify after I made the changes...

**Closed** 2015-06-29 12:27 UTC
Labels: bug
