### ISSUE TITLE
Conditional Resources - Validation

### ISSUE THREAD

**Issue by bladerunner918** [ewoutkramer/fhir-net-api#617] opened 2018-06-06 15:44 UTC
There seems to be an oversight in the validator when supplying conditional references in transaction bundles. For example if the conditional reference requires the lookup of a resource dependent on the matching of more than one property using the | (pipe) character (such as system|value in Identifier element) the validation fails.

<patient>
<reference value="Patient?identifier=https://project/patientIDs|4" />
</patient> 
response is Error - Invalid with the following reason:
"text": "Encountered an unparseable reference (Patient?identifier=https://project/patientIDs|4)"

However the upload transaction seems to work as expected. I believe this to be caused by the validator enforcing URL compliance which may not be suitable here.

Stephen

**Comment by ewoutkramer** [comment] 2018-06-07 10:56
Your analysis is probably correct!

**Comment by ewoutkramer** [comment] 2018-06-07 15:15
Well, that would be a change to the specification....

**Comment by ewoutkramer** [comment] 2018-07-30 11:33
The problem is that we use `Uri.IsWellformedUriString()` function to check for validity of the reference. Indeed, using an _unescaped_ `|` makes the uri invalid.  In the definition of Reference.reference in the FHIR spec, it's unclear whether the uri needs to be escaped, so we cannot be sure nor enforce any reference coming in to be propertly escaped.

So the proposed resolution is to escape this string *before* we feed it into the (relevant parts of) the validator.

**Comment by ewoutkramer** [comment] 2018-08-01 12:26
Fixed by #656.

**Closed by ewoutkramer** 2018-08-01 12:26 UTC
Labels: bug
