### ISSUE TITLE
XML Serializer generates an empty meta tag.

### ISSUE THREAD

**Issue by mharthoorn** [ewoutkramer/fhir-net-api#431] opened 2017-09-22 08:16 UTC
When you serialize a POCO that does not have any meta fields, an empty meta tag <meta /> is generated in the XML output.

**Comment by brianpos** [comment] 2017-09-23 00:46
Try that with the updated changes input in a day or so ago.

**Comment by ewoutkramer** [comment] 2017-09-27 07:37
Does this have to do with the changes  Emanuel made?

**Comment by brianpos** [comment] 2017-09-27 08:21
Yes i believe so.

**Comment by ewoutkramer** [comment] 2017-09-27 14:10
No, this "bug" has been around for a long time.  The serializer will produce an empty element if you create one, so:

    vs.Meta = new Meta();
    var xml = (new FhirXmlSerializer()).Serialize(vs);
   
will result in an empty Meta tag.  I did find a few places in our code where we add empty Meta's (i.e. for the SUBSETTED operation - see #434)

This is not easy to fix - we basically need an IsEmpty() on every element - the Java library has this, but we have not added this feature to .NET yet...

**Comment by brianpos** [comment] 2017-09-27 21:50
But the change that emanual made always creates the Meta, and then it doesn't populate due to the summary types.
So it got worse as a result of the change.

**Comment by brianpos** [comment] 2017-09-27 21:50
as that codepath created a new meta resource (and doesn't cleanup after itself)

**Comment by ewoutkramer** [comment] 2017-10-26 16:36
So, the extra Meta that was added - that has been fixed. The larger issue (no checking of whether an Element is empty) has *not* been fixed - and is in fact harder to fix. Need to change the code generator for the POCOs to generate a method IsEmpty()......

**Comment by ewoutkramer** [comment] 2017-10-26 16:37
See also #354 for a related issue.

**Comment by ewoutkramer** [comment] 2017-10-26 16:51
Actually, this is a duplicate of #87. We'd need this to fix the parser....

**Comment by ewoutkramer** [comment] 2018-11-21 12:48
With the new parser/serialization framework in 1.0, this is fixed: the tree is pruned from empty elements before serialization.

**Closed by ewoutkramer** 2018-11-21 12:48 UTC
Labels: enhancement
