### ISSUE TITLE
Validation: incorrect warning when extension definition snapshot is missing

### ISSUE THREAD

**Issue by wmrutten** [ewoutkramer/fhir-net-api#427] opened 2017-09-18 13:00 UTC
Thomas Tveit Rosenlund reported an error on Zulip Conformance stream:
https://chat.fhir.org/#narrow/stream/implementers/subject/extensions

I've downloaded the example and profiles locally and ran the offline .NET Profile Validation Tool (v1.4).
Initially the validator reports three warnings:

- [ERROR] Profile 'http://ehelse.no/fhir/vft/STU3/StructureDefinition/vft-timestamp' does not include a snapshot. (at Flag.extension[0])
- [ERROR] Profile 'http://ehelse.no/fhir/vft/STU3/StructureDefinition/vft-timestamp' does not include a snapshot. (at Flag.extension[1])
- [ERROR] Instance count for 'Flag.extension:kodeverdi-obligatorisk' is 2, which is not within the specified cardinality of 1..1 (at Flag)

Then I used Forge to generate the missing snapshot component for the vft-timestamp extension definition and re-ran the validator. Now the validation tool reports SUCCESS.

BUGS:
1. Warning (2) is incorrect, element Flag.extension[1] refers to a DIFFERENT extension definition "vft-quantityspeedms-ext" which has a snapshot component.
2. Warning (3) about extension element cardinality violation is incorrect. As the cardinality is defined by the test-flag profile, and not by the extension definition, the validator shouldn't even need access to the extension definition in order to correctly verify the extension element cardinality.

I'd expect the validator to only report the first warning, about missing snapshot component in extension definition vtf-timestamp.

**Comment by ewoutkramer** [comment] 2017-12-05 09:31
I cannot reproduce any of this based on the current state of the norwegian project mentioned (at https://simplifier.net/Velferdsteknologi2).  Also, the example mentioned in the zulip chat cannot be right (it uses an extension with a child url "kodeverdi", without being nested in an extension with a proper url.  

I have ran the "Flag-Trondheim-example.xml" example in the velferdsteknologi2 project, and the messages coming out (in v1.4) seem to be correct, even if I remove the snapshots and disable snapshot generation.

I have written Thomas about this, asking whether the problem still persists. Until I hear a response, I am closing this issue because it's not reproducible (anymore) for me.

**Closed by ewoutkramer** 2017-12-05 09:31 UTC
Labels: bug
