### ISSUE TITLE
Validator: Error on missing code while the code element is not mandatory

### ISSUE THREAD

**Issue by LilianMinne** [ewoutkramer/fhir-net-api#678] opened 2018-08-23 14:00 UTC
The following example (based on the https://simplifier.net/HL7Norwayno-basis/no-basis-Patient profile) validates correctly: https://simplifier.net/velferdsteknologi2/patient-example-duplicate-2
But when the (not mandatory) code element is removed from the no-basis-bydel extension the validator complains that the code element is not present.

**Comment by ewoutkramer** [comment] 2018-11-23 13:55
Duplicate of #559.

**Closed by ewoutkramer** 2018-11-23 13:55 UTC
Labels: [Validator], duplicate
