### ISSUE TITLE
FhirBoolean's cause DotNetAttributeValidation.TryValidate to throw an ArgumentException

### ISSUE THREAD

**Issue by samuelbcollie** [ewoutkramer/fhir-net-api#577] opened 2018-04-12 15:22 UTC
**This is in develop-r4**

BooleanPatternAttribute is passed a bool instead of a string, causing the validation to fail outright.

    [AttributeUsage(AttributeTargets.Property, Inherited = false, AllowMultiple = false)]
    public class BooleanPatternAttribute : ValidationAttribute
    {
        protected override ValidationResult IsValid(object value, ValidationContext validationContext)
        {
            if (value == null) return ValidationResult.Success;

            if (value.GetType() != typeof(string)) //<----HERE
                throw new ArgumentException("BooleanPatternAttribute can only be applied to string properties");

            if (FhirBoolean.IsValidValue(value as string))
                return ValidationResult.Success;
            else
				return DotNetAttributeValidation.BuildResult(validationContext, "{0} is not a correctly formatted Boolean", value as string);
        }
    }

**Comment by ewoutkramer** [comment] 2018-04-12 15:55
@brianpos - this has changed in the code generation somehow. I found where, and can remove it, but I am interested in whether this appears elsewhere too.....

**Comment by ewoutkramer** [comment] 2018-04-12 15:56
The problem is not the statement above, but the fact that FhirBoolean.Value (in the generated code for FhirBoolean) is now adorned with a `BooleanPattern` attribute. This should not be the case - and was not in STU3.

**Comment by brianpos** [comment] 2018-04-12 19:32
I did have to do some minor mods to the code generations this time.
I'd check the other primitive data types too then.

**Comment by ewoutkramer** [comment] 2018-06-06 12:36
@brianpos - I did a quick fix for this in #616, but have no clue why this did not happen in STU3, T4 code seems to be unchanged in this respect.

**Closed** 2018-06-06 15:42 UTC
Labels: bug
