### ISSUE TITLE
Create throws an exception if the server doesn't return a body

### ISSUE THREAD

**Issue by wdebeau1** [ewoutkramer/fhir-net-api#77] opened 2015-04-30 18:12 UTC
Creating resources on http://fhirtest.uhn.ca/baseDstu2 doesn't return a body. According to http://www.hl7.org/FHIR/2015May/http.html#create, returning a body seems to be optional.
However, an exception is thrown after the resource is created such as
Operation POST on http://fhirtest.uhn.ca/baseDstu2/QuestionnaireAnswers expected a body but none was returned

**Comment by mharthoorn** [comment] 2015-05-01 08:34
Yes. I noticed this too. I created a temporary work around on Spark - to always include the body. But I aggree that the client should not demand it.

**Comment by ewoutkramer** [comment] 2015-05-04 11:13
The client has a "ReturnFullResource" property that it uses to know whether to expect a full body. Maybe the API is too strict in that it uses this property to *demand* the server returns a body. I will look into this.

**Comment by ewoutkramer** [comment] 2015-05-10 07:55
This is actually a duplicate of #64, I am going to fix both now.

**Closed by ewoutkramer** 2015-05-10 07:55 UTC
Labels: bug
