### ISSUE TITLE
Validation of ref-1 fails for contained resources

### ISSUE THREAD

**Issue by brianpos** [ewoutkramer/fhir-net-api#432] opened 2017-09-25 02:45 UTC
The below example fails to validate
http://hl7.org/fhir/activitydefinition-medicationorder-example.xml.html

I expect this is due to the contained reference is within the contained collection.

**Comment by ewoutkramer** [comment] 2017-09-26 12:16
Duplicate of #423?

**Comment by brianpos** [comment] 2017-09-26 12:51
Yes

**Closed** 2017-09-26 14:00 UTC
