### ISSUE TITLE
Patient Resource - some Extentions are missing

### ISSUE THREAD

**Issue by sandeepac** [ewoutkramer/fhir-net-api#323] opened 2017-04-11 11:24 UTC
"url": "http://varian.com/fhir/StructureDefinition/patient-status",
            "url": "http://varian.com/fhir/StructureDefinition/patient-patientType",
            "url": "http://varian.com/fhir/StructureDefinition/patient-isInPatient",
            "url": "http://varian.com/fhir/StructureDefinition/patient-patientTimeStamp",
I a m able to see the above extensions in extension list array

            "url": "http://varian.com/fhir/StructureDefinition/patient-complaints",
I a m not able to see the above extension in the extension list array

**Comment by mbaltus** [comment] 2017-04-11 13:38
Can you give some more details about what you're trying to do, for example which API methods you are using, so we can investigate the issue?

**Comment by ewoutkramer** [comment] 2017-06-28 09:02
Closing this issue, as we have not heard from the author again and we cannot reproduce based on the current comment.

**Closed by ewoutkramer** 2017-06-28 09:02 UTC
